In [1]:
import numpy as np

In [3]:
scalar = np.array(42)
print(scalar)
scalar.ndim

42


0

In [4]:
vector = np.array([42,3,3 ,5,6])
print(vector)
vector.ndim

[42  3  3  5  6]


1

In [8]:
matrix = np.array([[42,3,3 ,5,6],[4,13,23 ,35, 7]])
print(matrix)
matrix.ndim

[[42  3  3  5  6]
 [ 4 13 23 35  7]]


2

tensor 3d


In [25]:
tensor_3 = np.array([[[11,3,3 ,5,6],[22,13,23 ,35, 7]],[[21,2,3 ,5,6],[22,13,23 ,35, 7]],[[31,3,3 ,5,6],[32,13,23 ,35, 7]],[[41,3,3 ,5,6],[42,13,23 ,35, 7]]])
print(tensor_3)
tensor_3.ndim

[[[11  3  3  5  6]
  [22 13 23 35  7]]

 [[21  2  3  5  6]
  [22 13 23 35  7]]

 [[31  3  3  5  6]
  [32 13 23 35  7]]

 [[41  3  3  5  6]
  [42 13 23 35  7]]]


3

In [32]:
tensor_3[1,1,3]

35

tensor_4d 

In [33]:
tensor_4 = np.array([[[[11,3,3 ,5,6],[22,13,23 ,35, 7]],[[21,2,3 ,5,6],[22,13,23 ,35, 7]],[[31,3,3 ,5,6],[32,13,23 ,35, 7]],[[41,3,3 ,5,6],[42,13,23 ,35, 7]],[[11,3,3 ,5,6],[22,13,23 ,35, 7]],[[21,2,3 ,5,6],[22,13,23 ,35, 7]],[[31,3,3 ,5,6],[32,13,23 ,35, 7]],[[41,3,3 ,5,6],[42,13,23 ,35, 7]]]])
print(tensor_4)
tensor_4.ndim

[[[[11  3  3  5  6]
   [22 13 23 35  7]]

  [[21  2  3  5  6]
   [22 13 23 35  7]]

  [[31  3  3  5  6]
   [32 13 23 35  7]]

  [[41  3  3  5  6]
   [42 13 23 35  7]]

  [[11  3  3  5  6]
   [22 13 23 35  7]]

  [[21  2  3  5  6]
   [22 13 23 35  7]]

  [[31  3  3  5  6]
   [32 13 23 35  7]]

  [[41  3  3  5  6]
   [42 13 23 35  7]]]]


4

In [36]:
tensor_4[0]

array([[[11,  3,  3,  5,  6],
        [22, 13, 23, 35,  7]],

       [[21,  2,  3,  5,  6],
        [22, 13, 23, 35,  7]],

       [[31,  3,  3,  5,  6],
        [32, 13, 23, 35,  7]],

       [[41,  3,  3,  5,  6],
        [42, 13, 23, 35,  7]],

       [[11,  3,  3,  5,  6],
        [22, 13, 23, 35,  7]],

       [[21,  2,  3,  5,  6],
        [22, 13, 23, 35,  7]],

       [[31,  3,  3,  5,  6],
        [32, 13, 23, 35,  7]],

       [[41,  3,  3,  5,  6],
        [42, 13, 23, 35,  7]]])

add or delete dimensions


In [40]:
tensor_10 = np.array([42,3,3 ,5,6],ndmin = 10)
print(tensor_10)
tensor_10.ndim

[[[[[[[[[[42  3  3  5  6]]]]]]]]]]


10

axis = 0 dimentions in rows
axis = 1 dimentions in columns

In [41]:
expand = np.expand_dims(np.array([42,3,3 ,5,6]), axis = 0)
print(expand)
expand.ndim

[[42  3  3  5  6]]


2

if we want eleminate all dimensions we are not using so far let see 

In [42]:
print(tensor_10, tensor_10.ndim)
vector_n = np.squeeze(tensor_10)
print(vector_n, vector_n.ndim)

[[[[[[[[[[42  3  3  5  6]]]]]]]]]] 10
[42  3  3  5  6] 1


example, lets remember how to expands 
axis = 0 dimentions in rows
axis = 1 dimentions in columns

In [51]:
matrix_1 = np.array([0,1,2 ,3,4],ndmin = 2)
print('matrix 1 ',matrix_1)
exp_mtx1 = np.expand_dims(np.array(matrix_1), axis = 0)
print('exp_mtx1 ',exp_mtx1)
tensor_7 = np.array([0,1,2 ,3,4],ndmin = 7)
print('tensor7 -> ',tensor_7, 'dimension ', tensor_7.ndim)

exp_tnsr7 = np.expand_dims(np.array(tensor_7), axis = 1)
print('exp_tnsr7 ',exp_tnsr7,' dimension number ', exp_tnsr7.ndim)
vector_x = np.squeeze(exp_tnsr7)
print('excuting squeeze to exp_tnsr7 ',vector_x, vector_x.ndim)

matrix 1  [[0 1 2 3 4]]
exp_mtx1  [[[0 1 2 3 4]]]
tensor7 ->  [[[[[[[0 1 2 3 4]]]]]]] dimension  7
exp_tnsr7  [[[[[[[[0 1 2 3 4]]]]]]]]  dimension number  8
excuting squeeze to exp_tnsr7  [0 1 2 3 4] 1
